### PR TITLE
Fix for fin undefined on useInterApplicationBus hooks

### PR DESCRIPTION
**Pull request by darrenfurr**
@ColinEberhardt -
I added checks for fin on window to useInterApplicationBus hooks, so we can run outside of openfin for UI automation program.

### CODE REVIEW

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Darren Furr

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by ColinEberhardt** [comment]
Hi @darrenfurr thank you for this fix, that's great - sorry it's taken so long to look at this PR. This project required that people who contribute code sign a Contribution Compliance Agreement, as described here:

https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-ContributorLicenseAgreement

Is this something you'd be happy to sign so that we can accept your commit? Thanks.

**Comment by darrenfurr** [comment]
@ColinEberhardt - Checking with my employer. I don't think it will be a problem. I'll let you know.

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Darren Furr

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by finos-admin** [comment]
The cla-bot has been summoned, and re-checked this pull request!

**Comment by finos-admin** [comment]
Thank you for your contribution and **Welcome to our Open Source Community!**

To make sure your pull request is successful, we need all our contributors to be identifiable, but we couldn't parse the GitHub details of the following people : Darren Furr

Luckily, resolving the issue is straightforward and you can resolve it by following the instructions below.

1. Check your git client is configured with a user email `git config --list | grep email`
2. If the user email is missing, run the following command, substituting with your git commit email address `git config --global user.email email@example.com`
3. Make sure your git commit email is configured on GitHub by [Setting your Commit Email Address](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address)
4. Then, amend the authors in your commit history by using `git commit --amend` to change your last commit.

Alternatively, use the slightly more complex `git reset --soft` and `git rebase` to checkout your changes, rewrite the commit history locally and (force) push changes to the downstream branch.

If you have any issues with the steps above, please email [help@finos.org](mailto:help@finos.org) so we can help you resolve before reviewing and accepting your pull request.

Thanks once again for the contribution and understanding.

_cc_ **@finos-admin**

**Comment by maoo** [comment]
@finos-cla-bot[bot] check

**Comment by finos-admin** [comment]
The cla-bot has been summoned, and re-checked this pull request!

**Comment by maoo** [comment]
@darrenfurr , we got a green light! Thanks for your first contribution! FYI @ColinEberhardt

**Comment by ColinEberhardt** [comment]
Nice one - thanks @darrenfurr - much appreciated!

**Pull request merged**
